---
title: 'Convert measure.xls data from panel form and save as TXT file'
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 4
    fig_caption: true
    number_sections: true
my-var: "monte"  # https://bookdown.org/yihui/rmarkdown/html-document.html
---

```{r, chunk-get-keys}
#from Monte's!

path.measure = "C:/gitfolder/WSU_STATS419_FALL2020/Project1/";  
  # change this to wherever measure.xls lives for you...  
  # YOU SHOULD USE MINE IN THE DROPBOX AS THE EXAMPLE...
file.measure = paste0(path.measure,"measure_Prof.xlsx"); #monte's measure from dropbox
  # BELOW, we will import yours ...

library(readxl);

covariates = read_excel(file.measure, sheet="covariates"); #sheets: Panel and Covariates
panel = read_excel(file.measure, sheet="panel");

# these are currently in "tibble form"

covariates = as.data.frame(covariates);
panel = as.data.frame(panel);

#library(humanVerseWSU);

panel.first = panel$`person_id`[1];  # 1c2408654ef5a2fe1fc962088312266c -> shaffer's #

temp = panel[panel$`person_id` == panel.first , ]; #df of the first person 

mySide = (panel$side); #side variable
myKeys = (panel$mkey); #mkey variable

myJointKeys =  unique( paste0(myKeys,"-",mySide) );

## we know these are an exhaustive list of keys ...
  # covariates have 13 variables ...
  # side + jointkeys (23) + values 
tabularized.df = data.frame( matrix(NA, nrow=0, ncol=37) );
  tabularized.cols = c( colnames(covariates)[1:2], "side", myJointKeys, colnames(covariates)[3:13]); 
colnames(tabularized.df) = tabularized.cols;

```
Using the sample file provided, we have all the known keys.  Now, we will use those keys and "flatten" the covariates and panel into one dataframe that has lots of columns (37).

```{r, chunk-get-your-data}

  # MINE!

path.your.measure = "C:/_git_/STUDENTS";   # trailing slash or not?
path.your.measure = "C:/gitfolder/WSU_STATS419_FALL2020/Project1"

file.your.measure = paste0(path.your.measure,"/","measure2.xlsx"); # if no trailing slash, notice the "/"


covariates = read_excel(file.your.measure, sheet="covariates");
panel = read_excel(file.your.measure, sheet="panel");

# these are currently in "tibble form"

covariates = as.data.frame(covariates);
panel = as.data.frame(panel);


n.cov = dim(covariates)[1]; #num of rows in 
for(i in 1:n.cov) #n.cov = num ob observations
  {
     covariates.row = covariates[i,];

  final.row = as.data.frame( t(rep("NA",37)) ); #df of transpose of "NA" 37 times
  colnames(final.row) = tabularized.cols;

  final.row$`data_collector` = collector = covariates.row$`data_collector`;
  final.row$`person_id` = person = covariates.row$`person_id`;
  final.row[27:37] = covariates.row[3:13]; #fills in covariates, first 27 columns are blank

  subpanel = panel[panel$data_collector == collector & panel$person_id == person, ]; #messes up here
  n.sub = dim(subpanel)[1]; #ncols of subpanel #changed from 0 to 1
  for(j in 1:n.sub) 
    {
    subpanel.row = subpanel[j,]; # row j, all columns
      s = subpanel.row$side; #side
      k = subpanel.row$mkey; #head.height, etc.
      jk = paste0(k,"-",s); # hand.span-left
      v = subpanel.row$mvalue; 
    final.row$side = s;
    final.row[jk] = v;
    }

  tabularized.df = rbind(tabularized.df, final.row);

  }
  tabularized.df;
str(tabularized.df);

## verify your data ... make certain it seems to make sense
## make certain notes or other fields don't have the "|" pipe character


# save as a TXT file, pipe-delimited using your data_collector id

collector = "b7ae3660cd0f700f69ad759867c79192";
outfile = paste0(path.measure,"/","measure","-",collector,".txt");

utils::write.table( tabularized.df , file=outfile, quote=FALSE, col.names=TRUE, row.names=FALSE, sep="|");

# SUBMIT THIS FILE as measure-txt homework...


```